sudo: required
services:
  - docker

before_install:
  - docker build -t vacic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vacic/react-test npm run test

after_success:
  - docker build -t vacic/multi-client ./client
  - docker build -t vacic/multi-nginx ./nginx
  - docker build -t vacic/multi-server ./server
  - docker build -t vacic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push vacic/multi-client
  - docker push vacic/multi-nginx
  - docker push vacic/multi-server
  - docker push vacic/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-405490061087"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
